#!/usr/bin/env bash
id=$(xdotool search --class scratchterm)

if [ "$id" != "" ]
 then
  bspc node "$id" --flag hidden -f
else
  setsid st -c scratchterm -e tmux -f ~/.config/tmux/tmux.conf new -s scratchpad &
  bspc node "$id" --flag hidden -f
fi
