#!/bin/bash

[[ $BLOCK_BUTTON = "1" ]] && st -e sudo apt upgrade && updatecheck && pkill -RTMIN+13 i3blocks & disown

if [ ! -f /tmp/aptlist ]; then	aptlist="--"
else 	aptlist=$(cat /tmp/aptlist)
fi

#[ "${aptlist}" != "0" ] &&
[ "${aptlist}" != "" ] && echo "📦 ${aptlist}"
