#!/bin/bash
# Source: http://askubuntu.com/a/450136

therm_status="$(acpi -t | awk -F '[[:space:]]+|,' '{ print $5 }')"
therm_status="${therm_status:0:2}"

URGENT_VALUE=90

PREV_TOTAL=0
PREV_IDLE=0

cpuFile="/tmp/.cpu"

if [[ -f "${cpuFile}" ]]; then
  fileCont=$(cat "${cpuFile}")
  PREV_TOTAL=$(echo "${fileCont}" | head -n 1)
  PREV_IDLE=$(echo "${fileCont}" | tail -n 1)
fi

CPU=(`cat /proc/stat | grep '^cpu '`) # Get the total CPU statistics.
unset CPU[0]                          # Discard the "cpu" prefix.
IDLE=${CPU[4]}                        # Get the idle CPU time.

# Calculate the total CPU time.
TOTAL=0

for VALUE in "${CPU[@]:0:4}"; do
  # shellcheck disable=SC2219
  let "TOTAL=$TOTAL+$VALUE"
done

if [[ "${PREV_TOTAL}" != "" ]] && [[ "${PREV_IDLE}" != "" ]]; then
  # Calculate the CPU usage since we last checked.
  # shellcheck disable=SC2219
  let "DIFF_IDLE=$IDLE-$PREV_IDLE"
  # shellcheck disable=SC2219
  let "DIFF_TOTAL=$TOTAL-$PREV_TOTAL"
  # shellcheck disable=SC2219
  let "DIFF_USAGE=(1000*($DIFF_TOTAL-$DIFF_IDLE)/$DIFF_TOTAL+5)/10"
  echo "💽 ${DIFF_USAGE}%   $therm_status°C"
  echo ""
else
  echo "?"
  echo "?"
  echo ""
fi

# Remember the total and idle CPU times for the next check.
echo "${TOTAL}" > "${cpuFile}"
echo "${IDLE}" >> "${cpuFile}"

if [[ "${DIFF_USAGE}" -gt 0 ]] && [[ "${DIFF_USAGE}" -gt "${URGENT_VALUE}" ]]; then
  exit 33
fi
