#!/bin/bash

[[ $BLOCK_BUTTON = "1" ]] && \
	notify-send "RAM" "$(ps axch -o cmd:15,%mem --sort=-%mem | sed 11q)"

	mem=$(free -h | awk '$1~/Mem/{print $3}')
	swap=$(free -h | awk '$1~/Swap/{print $3}')

	if [ "${swap}" == "0" ] || [ "${swap}" == "0B" ]
	then 	echo "🧠 ${mem}" | tr -d i
	else 	echo "🧠 ${mem}"\|\|"${swap}" |tr -d i
	fi
