#!/bin/bash

case $BLOCK_BUTTON in
	1) urxvt -e alsamixer & disown ;;
	3) smixer mute ;;
	4) smixer up 5;;
	5) smixer down 5 ;;
esac
	getVolume=$(amixer get Master state | sed -e "s/\[//;s/\]//" | awk '$1=="Front"&&$2=="Left:"{print $5}')
	getState=$(amixer get Master state | awk '$1=="Front"&&$2=="Left:"{print $6}')
# getVolume=$(amixer get Master state | awk '$1=="Front"&&$2=="Left:"{print $5}')
# getState=$(amixer get Master state | awk '$1=="Front"&&$2=="Left:"{print $6}')

	if [ "$getState" = "[off]" ]
	then 	echo "🔇${getVolume}"
	else	echo "🔈${getVolume}"
		fi
# [ "$getState" = "[off]" ] && echo [mute] && exit
# echo "$getVolume"
